### PR TITLE
[3510][15.0][UPD] stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Reflect with OCA.
[3510](https://www.quartile.co/web#id=3510&model=project.task&view_type=form&menu_id=)

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
The tests was failed when new company in tests case(multi company). After investigated root cause, the issue come from `partner_company_default`. When we create new company, system creates partner automatically before create company and assign to company. But partner_company_default assigns company during creation of partner and cause error when assign this partner to new company. I added this module to rebel_module_groups to solve that issue.

**Comment by yostashiro** [comment]
> The tests was failed when new company in tests case(multi company). After investigated root cause, the issue come from `partner_company_default`. When we create new company, system creates partner automatically before create company and assign to company. But partner_company_default assigns company during creation of partner and cause error when assign this partner to new company. I added this module to rebel_module_groups to solve that issue.

@AungKoKoLin1997 Isn't this something we should fix in partner_company_default module?

**Comment by AungKoKoLin1997** [comment]
I push commit for partner_company_default in this PR to check the CI situation.

**Comment by rinaldifirdaus** [comment]
Functional test: picking and invoice properly linked. issue when creating new company has been resolved as well.
Im going to apply this update to staging. Thanks
Module to be upgraded on staging:
1. stock_picking_invoice_link
2. partner_company_default

**Comment by AungKoKoLin1997** [comment]
@rinaldifirdaus I made some changes in OCA repo. Plase follow up https://github.com/OCA/partner-contact/pull/1544.

**Review by kanda999 — APPROVED** [review]
LGTM

**Pull request merged**
