### PR TITLE
[3363][IMP] report_csv: add encoding option

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Adjustment with OCA PR.
[3363](https://www.quartile.co/web#id=3363&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]

**Comment by yostashiro** [comment]
@rinaldifirdaus This should not break the existing implementation.  Please go ahead and upgrade the module in the test database.  Upon confirming that there is no issue, go ahead and do the same in the production database.

**Comment by rinaldifirdaus** [comment]
@yostashiro san @AungKoKoLin1997 , i updated the module on mi7 staging, but the same issue with the one that i got when upgrading psc staging occurs.
image

*I already restart the staging server before upgrade this module

error log:
Traceback (most recent call last):
  File "/odoo/code/odoo/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 1095

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/code/odoo/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/odoo/code/odoo/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.actions.report(1095,).name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/code/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/code/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/code/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/code/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/code/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/code/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/odoo/code/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/odoo/code/odoo/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/code/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/code/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/code/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_upgrade
  File "/odoo/code/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/code/odoo/odoo/addons/base/models/ir_module.py", line 662, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/odoo/code/odoo/odoo/addons/base/models/ir_module.py", line 599, in _button_immediate_function
    self._cr.commit()
  File "<decorator-gen-7>", line 2, in commit
  File "/odoo/code/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/odoo/code/odoo/odoo/sql_db.py", line 469, in commit
    self.flush()
  File "/odoo/code/odoo/odoo/sql_db.py", line 109, in flush
    self.transaction.flush()
  File "/odoo/code/odoo/odoo/api.py", line 833, in flush
    env_to_flush['base'].flush()
  File "/odoo/code/odoo/odoo/models.py", line 5644, in flush
    self.recompute()
  File "/odoo/code/odoo/odoo/models.py", line 6117, in recompute
    process(field)
  File "/odoo/code/odoo/odoo/models.py", line 6101, in process
    field.recompute(recs)
  File "/odoo/code/odoo/odoo/fields.py", line 1243, in recompute
    self.compute_value(recs)
  File "/odoo/code/odoo/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
  File "/odoo/code/odoo/odoo/models.py", line 4255, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/code/odoo/odoo/addons/base/models/ir_module.py", line 239, in _get_views
    module.reports_by_module = "\n".join(sorted(r.name for r in browse('ir.actions.report')))
  File "/odoo/code/odoo/odoo/addons/base/models/ir_module.py", line 239, in <genexpr>
    module.reports_by_module = "\n".join(sorted(r.name for r in browse('ir.actions.report')))
  File "/odoo/code/odoo/odoo/fields.py", line 1083, in __get__
    recs._fetch_field(self)
  File "/odoo/code/odoo/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
  File "/odoo/code/odoo/odoo/models.py", line 3343, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/odoo/code/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/odoo/code/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/code/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/code/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedColumn: column ir_act_report_xml.encode_error_handling does not exist
LINE 1: ...t", "ir_act_report_xml"."encoding" as "encoding", "ir_act_re...
                                                             ^

**Comment by yostashiro** [comment]
@rinaldifirdaus I experience the same error in the devel environment when I try to upgrade the module through Odoo UI (it's strange). Try upgrading the module through command and it should fix the error:

```
docker exec -u odoo -t odoo /odoo/code/odoo/odoo-bin -c /odoo/etc/odoo.conf -d mi7test12 --http-port=8070 -u report_csv --stop-after-init
```

**Comment by rinaldifirdaus** [comment]
@yostashiro san, Thank you! I've upgraded the module on mi7test12 with the mentioned command, and its working. I have try to download stock picking's YAMATO CSV report, and there were no error/issue occurs.
image

Kindly merge this PR to upgrade it on production as well. Thank you

**Comment by yostashiro** [comment]
@rinaldifirdaus Let's follow up on this PR tomorrow morning.

**Pull request merged**
