### PR TITLE
15.0 [REM] all OCA modules [ADD] OCA modules ver15

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[#2258](https://www.quartile.co/web#id=2258&action=771&model=project.task&view_type=form&menu_id=505)
- [x] git branch from 10.0
- [x] Remove all OCA modules and requirements.txt
- [x] ADD OCA modules of V15

### CODE REVIEW

**Comment by tack-yabeQuartile** [comment]
modules
- [ ] auditlog (no code for V15/ PR exists) ... `Necessity: Not Decided`
- [ ] auth_signup_verify_email (no code and PR for V15)
- [ ] auth_user_case_insensitive (no code and PR for V15) ... `Necessity: Not Decided`
- [x] base_technical_features ... `Necessity: Optional`
- [x] mail_debrand
- [x] queue_job
- [ ] report_csv (no code and PR for V15)
- [x] report_xlsx
- [x] sale_automatic_workflow
- [x] stock_no_negative
- [ ] stock_picking_invoice_link (no code for V15/ PR exists)
- [x] stock_split_picking
- [x] web_environment_ribbon ... `Necessity: Optional`
- [ ] web_favicon (no need.) ... `Necessity: Not Need`
- [x] web_m2x_options
- [ ] website_no_crawler(no code and PR for V15) ... `Necessity: Not Decided`
- [ ] website_sale_charge_payment_fee(no code and PR for V15)

**Comment by tack-yabeQuartile** [comment]
Scope on this PR
[MIG]
base_technical_features... `Necessity: Optional`
 mail_debrand
 queue_job
 report_xlsx
 sale_automatic_workflow
 stock_no_negative
 stock_split_picking
 web_environment_ribbon... `Necessity: Optional`
 web_m2x_options

[REM]
 auditlog (no code for V15/ PR exists)... `Necessity: Not decided`
 auth_signup_verify_email (no code and PR for V15)
 auth_user_case_insensitive (no code and PR for V15)... `Necessity: Not decided`
  report_csv (no code and PR for V15)
 stock_picking_invoice_link (no code for V15/ PR exists)
 web_favicon... `Necessity: Not need`
 website_no_crawler(no code and PR for V15)...`Necessity: Not decided`
 website_sale_charge_payment_fee(no code and PR for V15)

**Comment by yostashiro** [comment]
@tack-yabeQuartile We should split the PR into a few processable chunks.

- One to remove the modules we are not going to use
- One to override the content per module

We need to test and assess each module in the staging environment before moving it to the production, therefore it is not good to have all the modules in one PR.

**Comment by tack-yabeQuartile** [comment]
We proceed through individual PRs.

**Pull request closed without merging**
