### PR TITLE
15.0 [2258][MIG] base_technical_features

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[2258](https://www.quartile.co/web#id=2258&action=771&model=project.task&view_type=form&menu_id=)

To make easy to check the difference between V10 and V15, three commits were pushed.

Actions to make this PR.
1. remove the module (First commit)
2. re-add the module for V10 (Second commit) ... We can see the update in V10 when OCA module had some renewals.
3. remove the module and then migrate the module for V15 (third commit) ... We can see the differences along the remodeling from V10 to V15.

### CODE REVIEW

**Comment by tack-yabeQuartile** [comment]
Conclusion: No Logic seems to be changed.

Abstract of changed  points from V10 -> V15:
- Repository has been changed and some files are changed such as README, manifest.py and so on.
- Translation files
- Name of user account has updated as `base.user_root -> base.user_admin` (/data/res_users.xml)
- comma and styles are adjusted and "openerp" -> "odoo".
- Constructor method in /models/res_users.py has been taken place by thwo methods with @property decorator.
- a few files have been added in readme directory.
- [views/res_users.xml](https://github.com/qrtl/mi7-oca/pull/16/files#diff-11847ca42b941149edaae4f498bd2ca5ee183030d685dc154a644e22db43398b) have little change. An expression for xpath was updated.

**Review by yostashiro — APPROVED** [review]
👍

**Comment by yostashiro** [comment]
> 👍

@tack-yabeQuartile I did it too fast.  Shouldn't we first create a staging branch for 15.0 and create a PR targeting that?

**Comment by tack-yabeQuartile** [comment]
> Shouldn't we first create a staging branch for 15.0 and create a PR targeting that?

Yes, we should do so.
I once change the status of this PR from ready to draft and proceed updating from staging branch.

**Pull request merged**
